"use strict";

const DUR = /^(\d+(\.\d+)?(ns|us|ms|s|m|h))+$/;

// Header the server requires on writes. It is not a secret: a non-standard header
// forces the browser into a CORS preflight check, which a third-party site cannot
// pass — so it cannot make the interface write on our behalf.
const TOKEN = "frigate-telegram-enhanced";

// ---- langue -------------------------------------------------------------------
//
// Texts are written in English: T(`text`), or Tf(`text with %s and %d`, …); the
// fixed texts of the page carry data-t="text". i18n.js, generated by the service
// from its catalogs, provides LANGUAGES ([{code, name}]) and CATALOGS (code →
// English text → translation). The language follows the browser, unless one was
// picked with the selector, which this browser remembers.

const LANG_KEY = "frigate-telegram-enhanced-lang";
const CODES = LANGUAGES.map((l) => l.code);

function initialLang() {
  try {
    const saved = localStorage.getItem(LANG_KEY);
    if (CODES.includes(saved)) return saved;
  } catch (e) { /* storage unavailable: follow the browser */ }
  for (const pref of navigator.languages || [navigator.language || ""]) {
    const code = pref.toLowerCase().split("-")[0];
    if (CODES.includes(code)) return code;
  }
  return "en";
}

let lang = initialLang();
const T = (s) => (CATALOGS[lang] && CATALOGS[lang][s]) || s;
const Tf = (s, ...args) => { let i = 0; return T(s).replace(/%[sd]/g, () => String(args[i++])); };
const locale = () => (lang === "en" ? "en-GB" : lang);

function applyStatic() {
  document.documentElement.lang = lang;
  document.title = T("frigate-telegram-enhanced — notifications");
  for (const n of document.querySelectorAll("[data-t]")) n.textContent = T(n.dataset.t);
  for (const b of document.querySelectorAll(".lang button")) b.setAttribute("aria-pressed", String(b.dataset.lang === lang));
}

function setLang(l) {
  lang = l;
  try { localStorage.setItem(LANG_KEY, l); } catch (e) { /* choice not remembered, no harm done */ }
  applyStatic();
  if (!data) return;
  $("mode").textContent = T("mode ") + data.mode;
  render();
  renderLive();
  renderHistory();
  renderHealth();
  if (data.can_health) loadHealth(); // server messages: asked again in the new language
  touched();
}

// api is fetch with the page's language: the server answers its errors in the same one.
function api(path, opts) {
  opts = Object.assign({}, opts);
  opts.headers = Object.assign({"X-Lang": lang}, opts.headers || {});
  return fetch(path, opts);
}

// ---- styles and simple questions ---------------------------------------------
//
// Each choice is a small patch of settings. It is "active" when the effective
// settings match it; if none matches, the question shows "Custom" and points to the
// advanced settings.

// inPlace: the video (or GIF) replaces the image in the notification message.
const inPlace = () => !overlay || overlay.notify.media_in_place !== false;

const STYLES = () => [
  {id: "clip", label: T("Photo + video"), tag: T("Recommended"),
   desc: inPlace()
     ? T("The image right away, then the video takes its place in the same message.")
     : T("The image right away, then the video clip as a reply when the event ends."),
   patch: {snapshot: true, clip: true, gif: false}},
  {id: "photo", label: T("Photo only"),
   desc: T("Light. The clip stays one tap away with the 🎬 button."),
   patch: {snapshot: true, clip: false, gif: false}},
  {id: "gif", label: T("Photo + GIF"),
   desc: inPlace()
     ? T("The image, then a short animated preview in its place.")
     : T("A short animated preview instead of the video."),
   patch: {snapshot: true, clip: false, gif: true}},
  {id: "text", label: T("Text only"),
   desc: T("The most discreet: just the message and the buttons."),
   patch: {snapshot: false, clip: false, gif: false}},
];

const NIGHT = [{from: "22:00", to: "07:00"}];

const QUESTIONS = () => [
  {title: T("What should be reported?"), options: [
    {label: T("🚶 People"), patch: {labels: ["person"]}},
    {label: T("🚶🚗 People and cars"), patch: {labels: ["car", "person"]}},
    {label: T("Everything Frigate detects"), patch: {labels: []}},
  ]},
  {title: T("Which reviews?"), mode: "reviews", options: [
    {label: T("Alerts only"), patch: {severity: ["alert"]}},
    {label: T("Alerts and detections"), patch: {severity: ["alert", "detection"]}},
  ]},
  {title: T("How often, at most?"),
   hint: T("Per camera and per object type: further detections are ignored during this delay."),
   options: [
    {label: T("Every detection"), patch: {cooldown: "0s"}},
    {label: T("1 per minute"), patch: {cooldown: "1m"}},
    {label: T("1 every 10 min"), patch: {cooldown: "10m"}},
  ]},
  {title: T("Bursts"), more: true,
   hint: T("Detections close in time are added to the first message (edited, no new sound) instead of sending new ones."),
   options: [
    {label: T("One message per detection"), patch: {group: "0s"}},
    {label: T("📦 Group over 2 min"), patch: {group: "2m"}},
    {label: T("📦 Group over 5 min"), patch: {group: "5m"}},
  ]},
  {title: T("When someone is home"), presence: true,
   hint: T("Someone is home as soon as one of the presence topics says so (Home Assistant, sensor…)."),
   options: [
    {label: T("🔔 Notify as usual"), patch: {when_home: "notify"}},
    {label: T("🔕 Silent"), patch: {when_home: "silent"}},
    {label: T("🏠 Nothing"), patch: {when_home: "skip"}},
  ]},
  {title: T("At night (10 pm – 7 am)"), options: [
    {label: T("Same as daytime"), patch: {quiet_hours: [], off_hours: []}},
    {label: T("🔕 Silent"), patch: {quiet_hours: NIGHT, off_hours: []}},
    {label: T("🌙 No notifications"), patch: {quiet_hours: [], off_hours: NIGHT}},
  ]},
];

// Each detailed setting is described once and rendered twice: in the global advanced
// settings, and in each camera where it becomes an optional override.
const FIELDS = () => [
  {key: "enabled", type: "bool", name: T("Notifications enabled"),
   hint: T("Unchecked: no notifications at all (or none for this camera).")},
  {key: "chats", type: "chips", name: T("Recipients"), source: "chats",
   hint: T("Chats declared in TELEGRAM_CHAT_ID (or telegram.chats).")},
  {key: "labels", type: "chips", name: T("Objects"), source: "labels", free: true,
   hint: T("No object selected = every object is reported.")},
  {key: "zones", type: "chips", name: T("Zones"), source: "zones", free: true,
   hint: T("No zone selected = no constraint. Otherwise the object must have entered one of the zones.")},
  {key: "min_score", type: "score", name: T("Minimum score"), source: "labels"},
  {key: "cooldown", type: "duration", name: T("Delay between two notifications"),
   hint: T("Per camera and per object. E.g. 60s, 5m, 1h30m.")},
  {key: "ignore_sub_labels", type: "chips", source: "sub_labels", free: true,
   name: T("Don't notify for these labels"),
   hint: T("Frigate's labels (custom classification, faces, plates), e.g. your own car or cat.")},
  {key: "ignore_known", type: "bool", name: T("Only unknown objects"),
   hint: T("Every object Frigate recognizes (with a label) is ignored.")},
  {key: "sub_label_wait", type: "duration", name: T("Wait for the label"),
   hint: T("With a label filter, how long a notification waits for Frigate to recognize the object (e.g. 5s). Without a label by then, the object is unknown.")},
  {key: "ignore_stationary", type: "bool", name: T("Ignore stationary objects"),
   hint: T("Parked cars, garden furniture…")},
  {key: "severity", type: "chips", name: T("Severity"), source: "severity", mode: "reviews",
   hint: T("Which Frigate reviews trigger a notification.")},
  {key: "snapshot", type: "bool", name: T("Send the image")},
  {key: "crop", type: "bool", name: T("Crop the image on the object"),
   hint: T("Much more readable on a phone. Applies to event snapshots.")},
  {key: "clip", type: "bool", name: T("Send the video clip")},
  {key: "media_in_place", type: "bool", name: T("Video in the same message"),
   hint: T("The clip (or GIF) replaces the image in the notification, instead of arriving as a new message.")},
  {key: "gif", type: "bool", name: T("Send an animated GIF")},
  {key: "genai_description", type: "bool", name: T("Add the GenAI description"),
   hint: T("When Frigate publishes it, it is added to the notification's caption.")},
  {key: "group", type: "duration", globalOnly: true, name: T("Group bursts over"),
   hint: T("0s = one message per detection. Applies to every camera.")},
  {key: "clip_delay", type: "duration", name: T("Wait before fetching the clip"),
   hint: T("Gives Frigate time to finish the recording.")},
  {key: "when_home", type: "choice", name: T("When someone is home"), presence: true,
   choices: () => [["notify", T("Notify as usual")], ["silent", T("Silent")], ["skip", T("Nothing")]]},
  {key: "quiet_hours", type: "ranges", name: T("Quiet hours"),
   hint: T("Notifications sent without sound.")},
  {key: "off_hours", type: "ranges", name: T("Off hours"),
   hint: T("No notifications during these ranges.")},
];
const TYPES = Object.fromEntries(FIELDS().map((f) => [f.key, f.type]));

// The detailed settings, sorted by theme; `extra` adds what is not a notification
// setting (the link to Frigate, global only).
const GROUPS = () => [
  {title: T("Recipients and filtering"),
   keys: ["enabled", "chats", "labels", "zones", "min_score", "ignore_stationary", "severity"]},
  {title: T("Labels"), keys: ["ignore_sub_labels", "ignore_known", "sub_label_wait"]},
  {title: T("Media"),
   keys: ["snapshot", "crop", "clip", "media_in_place", "gif", "clip_delay", "genai_description"]},
  {title: T("Pace"), keys: ["cooldown", "group"]},
  {title: T("Schedule and presence"), keys: ["when_home", "quiet_hours", "off_hours"]},
  {title: T("Links"), keys: [], extra: () => externalURLField(), globalOnly: true},
];

let data = null;      // response of /api/settings
let overlay = null;   // what will be saved
let saved = null;     // serialization of the last saved state, to detect changes

const $ = (id) => document.getElementById(id);

function clone(v) { return JSON.parse(JSON.stringify(v)); }

function dirty() { return JSON.stringify(overlay) !== saved; }

// Every change is saved by itself, shortly after: no button to forget. Changes close
// together (several clicks in a row) leave as one save.
const SAVE_DELAY = 600;
let saveTimer = null;

function touched() {
  if (!dirty()) return;
  welcome = false; // the first change: the user found their way
  status(T("Saving…"), "dirty");
  clearTimeout(saveTimer);
  saveTimer = setTimeout(save, SAVE_DELAY);
}

function status(text, kind) {
  const s = $("status");
  s.textContent = text;
  s.className = "status" + (kind ? " " + kind : "");
}

function changed() { touched(); render(); }

function message(text, kind) {
  const box = $("messages");
  box.innerHTML = "";
  if (!text) return;
  const d = document.createElement("div");
  d.className = "notice " + kind;
  d.textContent = text;
  box.appendChild(d);
}

function el(tag, attrs, ...kids) {
  const n = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs || {})) {
    if (k === "class") n.className = v;
    else if (k === "text") n.textContent = v;
    else if (k.startsWith("on")) n.addEventListener(k.slice(2), v);
    else if (v !== null && v !== undefined) n.setAttribute(k, v);
  }
  for (const c of kids) if (c) n.append(c);
  return n;
}

// ---- comparing settings -------------------------------------------------------

// seconds converts a Go duration ("1m0s", "90s", "1h30m") into seconds, so that
// "1m" and "1m0s" are recognized as identical.
function seconds(d) {
  const unit = {ns: 1e-9, us: 1e-6, ms: 1e-3, s: 1, m: 60, h: 3600};
  let total = 0;
  for (const [, n, u] of String(d || "0s").matchAll(/(\d+(?:\.\d+)?)(ns|us|ms|s|m|h)/g)) total += Number(n) * unit[u];
  return Math.round(total * 1000) / 1000;
}

function norm(key, v) {
  switch (TYPES[key]) {
    case "duration": return seconds(v);
    case "chips": return (v || []).slice().sort();
    case "ranges": return v || [];
    case "bool": return !!v;
    default: return v;
  }
}

function same(key, a, b) { return JSON.stringify(norm(key, a)) === JSON.stringify(norm(key, b)); }

// effective returns the effective settings of the global level, or of a camera.
function effective(camera) {
  return camera ? Object.assign({}, overlay.notify, overlay.cameras[camera]) : overlay.notify;
}

function matches(patch, values) {
  return Object.entries(patch).every(([k, v]) => same(k, v, values[k]));
}

// apply sets a choice. For a camera, a choice identical to the global one removes
// the override rather than duplicating it: the camera then follows the global one.
function apply(patch, camera) {
  if (!camera) {
    Object.assign(overlay.notify, clone(patch));
    return;
  }
  const cam = overlay.cameras[camera];
  if (matches(patch, overlay.notify)) for (const k of Object.keys(patch)) delete cam[k];
  else Object.assign(cam, clone(patch));
}

function inheritsAll(patch, camera) {
  return Object.keys(patch).every((k) => !(k in overlay.cameras[camera]));
}

// ---- Telegram-like previews ---------------------------------------------------

function sampleCamera() {
  const cams = data.cameras || [];
  return cams.length ? cams[0].name : T("front door");
}

function preview(style) {
  const cam = sampleCamera();
  const p = style.patch;
  const tg = el("div", {class: "tg", "aria-hidden": "true"});

  const caption = el("div", {class: "cap"},
    el("b", {text: T("🚶 Person")}), document.createTextNode(" — " + cam),
    el("br"), document.createTextNode(T("📍 driveway · 87%")),
    el("br"), document.createTextNode("🕑 14:32:05"),
    el("br"), el("span", {class: "link", text: T("🔗 Open in Frigate")}));
  const kb = el("div", {class: "kb"}, el("span", {text: T("📷 Now")}), el("span", {text: "🎬 Clip"}));
  const kb2 = el("div", {class: "kb"}, el("span", {text: "🔇 1 h"}), el("span", {text: "⏸️ 30 min"}));

  // The video (or GIF) takes the image's place: a single message, shown at the end.
  const replaced = p.snapshot && (p.clip || p.gif) && inPlace();
  const first = el("div", {class: "bubble"});
  if (p.snapshot) {
    const zoom = overlay && overlay.notify.crop;
    const photo = el("div", {class: "photo" + (zoom ? " zoom" : "")}, el("div", {class: "bbox"}), el("div", {class: "who", text: "🚶"}));
    if (replaced && p.clip) photo.append(el("div", {class: "play", text: "▶"}), el("div", {class: "dur", text: "0:14"}));
    else if (replaced) photo.append(el("div", {class: "gif", text: "GIF"}));
    first.append(photo);
  }
  first.append(caption, kb, kb2);
  tg.append(first);

  if ((p.clip || p.gif) && !replaced) {
    const media = el("div", {class: "photo small"});
    if (p.clip) media.append(el("div", {class: "play", text: "▶"}), el("div", {class: "dur", text: "0:14"}));
    else media.append(el("div", {class: "who", text: "🚶"}), el("div", {class: "gif", text: "GIF"}));
    tg.append(el("div", {class: "bubble"}, el("div", {class: "quote", text: T("🚶 Person — ") + cam}), el("div", {style: "height:4px"}), media));
  }
  return tg;
}

// ---- notification d'essai ----------------------------------------------------

// The test goes out with the settings saved on the server: the pending changes are
// saved first.
function testButton(camera, label) {
  const wrap = el("span", {class: "try-one"});
  const result = el("span", {class: "result"});
  const btn = el("button", {type: "button", text: label || T("📨 Send me a sample")});
  btn.addEventListener("click", async (e) => {
    e.preventDefault();
    const cam = typeof camera === "function" ? camera() : camera;
    btn.disabled = true;
    result.className = "result"; result.textContent = T("Sending…");
    try {
      if (!(await flush())) throw new Error(T("the settings could not be saved"));
      const resp = await api("api/test", {
        method: "POST",
        headers: {"Content-Type": "application/json", "X-Requested-With": TOKEN},
        body: JSON.stringify({camera: cam}),
      });
      const body = await resp.json().catch(() => ({}));
      if (!resp.ok) throw new Error(body.error || "HTTP " + resp.status);
      result.className = "result ok"; result.textContent = T("Sent ✓ — check Telegram");
    } catch (err) {
      result.className = "result err"; result.textContent = T("Failed: ") + err.message;
    } finally {
      setTimeout(() => { btn.disabled = false; }, 3000);
    }
  });
  wrap.append(btn, result);
  return el("span", {class: "row"}, wrap);
}

function enabledCameras() {
  return (data.cameras || []).map((c) => c.name).filter((n) => effective(n).enabled !== false);
}

function renderTry() {
  const box = $("try");
  box.innerHTML = "";
  if (!data.can_test) return;
  const cams = enabledCameras();
  if (!cams.length) return;
  let pick = () => cams[0];
  if (cams.length > 1) {
    const sel = el("select", {"aria-label": T("Camera for the sample")});
    for (const c of cams) sel.append(el("option", {value: c, text: c}));
    pick = () => sel.value;
    box.append(testButton(() => pick()), el("span", {class: "hint", text: T("from camera")}), sel);
  } else {
    box.append(testButton(pick));
  }
}

// ---- rendering the simple choices ---------------------------------------------

function renderStyles() {
  const box = $("styles");
  box.innerHTML = "";
  const eff = effective(null);
  for (const st of STYLES()) {
    const active = matches(st.patch, eff);
    box.append(el("button", {
      type: "button", class: "style-card", "aria-pressed": String(active),
      onclick: () => { apply(st.patch, null); changed(); },
    },
      preview(st),
      el("div", {class: "meta"},
        el("div", {class: "title"}, el("span", {text: st.label}),
          st.tag ? el("span", {class: "tag", text: st.tag}) : null,
          el("span", {class: "check", text: "✓"})),
        el("div", {class: "desc", text: st.desc}))));
  }
  if (!STYLES().some((st) => matches(st.patch, eff))) {
    box.append(el("p", {class: "hint", text: T("Current setting is custom (see Advanced settings).")}));
  }
}

// externalURLField: the Frigate address used by the "Open in Frigate" link of the
// notifications. Empty, it is the one the service reaches Frigate at (FRIGATE_URL).
function externalURLField() {
  const valid = (u) => u === "" || /^https?:\/\/[^\s/]+/i.test(u);
  const input = el("input", {type: "url", class: "url", placeholder: data.frigate_url || "https://frigate.example.com",
    "aria-label": T("Frigate address for links")});
  input.value = overlay.external_url || "";
  const test = el("a", {class: "test", target: "_blank", rel: "noopener", text: T("Test ↗")});
  const sync = () => {
    const u = input.value.trim() || data.frigate_url || "";
    test.hidden = !u || !valid(u);
    test.href = u || "#";
  };
  sync();
  input.addEventListener("input", sync);
  input.addEventListener("change", () => {
    const u = input.value.trim().replace(/\/+$/, "");
    if (!valid(u)) { input.setCustomValidity(T("Expected an address like https://frigate.example.com")); input.reportValidity(); return; }
    input.setCustomValidity("");
    overlay.external_url = u;
    changed();
  });
  return el("div", {class: "field"},
    el("div", {class: "field-head"}, el("span", {class: "name", text: T("“Open in Frigate” link")})),
    el("div", {class: "control"}, input, test),
    el("p", {class: "hint", text: T("Empty: Frigate's address (FRIGATE_URL). Set another one to open Frigate from outside.")}));
}

// renderFraming: image framing and video placement, for the styles concerned.
function renderFraming() {
  const box = $("framing");
  box.innerHTML = "";
  const n = overlay.notify;
  if (!n.snapshot) return;
  const more = moreBox("framing", T("More choices: framing, video placement"));
  box.append(more);
  if (n.snapshot) {
    more.append(el("div", {class: "row"}, el("span", {class: "hint", text: T("Framing:")}),
      pills([
        {label: T("🖼 Wide shot"), patch: {crop: false}},
        {label: T("🔍 Zoom on the object"), patch: {crop: true}},
      ], null)));
  }
  if (n.snapshot && (n.clip || n.gif)) {
    more.append(el("div", {class: "row"}, el("span", {class: "hint", text: T("Video:")}),
      pills([
        {label: T("🔁 In the same message"), patch: {media_in_place: true}},
        {label: T("↩️ As a reply"), patch: {media_in_place: false}},
      ], null)));
  }
}

// pills renders a group of exclusive choices. For a camera, "Default" first removes
// the override.
function pills(options, camera) {
  const eff = effective(camera);
  const wrap = el("div", {class: "pills"});
  let any = false;
  if (camera) {
    const keys = Object.assign({}, ...options.map((o) => o.patch));
    const inherit = inheritsAll(keys, camera);
    any = inherit;
    wrap.append(el("button", {
      type: "button", class: "pill", "aria-pressed": String(inherit), text: T("Default"),
      onclick: () => { for (const k of Object.keys(keys)) delete overlay.cameras[camera][k]; changed(); },
    }));
  }
  for (const o of options) {
    const active = !any && matches(o.patch, eff);
    any = any || active;
    wrap.append(el("button", {
      type: "button", class: "pill", "aria-pressed": String(active), text: o.label,
      onclick: () => { apply(o.patch, camera); changed(); },
    }));
  }
  if (!any) wrap.append(el("span", {class: "pill custom", "aria-pressed": "true", text: T("Custom")}));
  return wrap;
}

// zonePills: "Everywhere" or a selection of the camera's zones (multiple choice).
function zonePills(camera, zones) {
  const cam = overlay.cameras[camera];
  const current = effective(camera).zones || [];
  const set = (next) => {
    if (same("zones", next, overlay.notify.zones)) delete cam.zones;
    else cam.zones = next;
    changed();
  };
  const wrap = el("div", {class: "pills"});
  wrap.append(el("button", {type: "button", class: "pill", "aria-pressed": String(!current.length),
    text: T("Everywhere"), onclick: () => set([])}));
  for (const z of zones) {
    const on = current.includes(z);
    wrap.append(el("button", {type: "button", class: "pill", "aria-pressed": String(on), text: "📍 " + z,
      onclick: () => set(on ? current.filter((x) => x !== z) : current.concat([z]))}));
  }
  for (const z of current) if (!zones.includes(z)) {
    wrap.append(el("button", {type: "button", class: "pill", "aria-pressed": "true", text: "📍 " + z + T(" (unknown)"),
      title: T("Zone missing from Frigate: click to remove it"),
      onclick: () => set(current.filter((x) => x !== z))}));
  }
  return wrap;
}

// moreBox is a folded "More choices" box: the settings a beginner can leave as
// they are. The page is redrawn on every change: the box remembers whether it was
// opened, under key. open: opened the first time.
const opened = {};
function moreBox(key, label, open) {
  const d = el("details", {class: "more"}, el("summary", {text: label}));
  d.open = key in opened ? opened[key] : !!open;
  d.addEventListener("toggle", () => { opened[key] = d.open; });
  return d;
}

function question(title, hint, content) {
  const q = el("div", {class: "question"}, el("div", {class: "q", text: title}), content);
  if (hint) q.append(el("p", {class: "hint", text: hint}));
  return q;
}

// ---- sensitivity ----------------------------------------------------------------

// scoredHistory: the recent detections that have a score (events mode).
function scoredHistory() {
  return (history || []).filter((e) => e.score > 0);
}

// sensitivityEffect describes, on the recent activity, the effect of a minimum score.
function sensitivityEffect(threshold) {
  const scored = scoredHistory();
  if (!scored.length) {
    return T("Recent activity will show the effect of this setting once there are detections.");
  }
  const dropped = scored.filter((e) => e.score < threshold);
  const lost = dropped.filter((e) => e.sent).length;
  if (!dropped.length) {
    return Tf("None of the last %d detections would be ignored for a low score.", scored.length);
  }
  if (lost) {
    return Tf("Out of the last %d detections, %d would be ignored for a low score, including %d that were sent.",
      scored.length, dropped.length, lost);
  }
  return Tf("Out of the last %d detections, %d would be ignored for a low score.", scored.length, dropped.length);
}

function sensitivity() {
  const ms = overlay.notify.min_score || {default: 0};
  if (ms.by_label && Object.keys(ms.by_label).length) {
    return el("p", {class: "hint", text: T("Set per object in Advanced settings.")});
  }
  const pct = (v) => Math.round(v * 100) + T("%");
  const range = el("input", {type: "range", min: "0", max: "0.95", step: "0.05",
    "aria-label": T("Minimum score")});
  range.value = ms.default || 0;
  const val = el("span", {class: "val", text: pct(Number(range.value))});
  const effect = el("p", {class: "hint sens-effect", text: sensitivityEffect(Number(range.value))});
  // While dragging, only the text is updated: redrawing the page would make the
  // user lose the slider. The value is kept on release.
  range.addEventListener("input", () => {
    val.textContent = pct(Number(range.value));
    effect.textContent = sensitivityEffect(Number(range.value));
  });
  range.addEventListener("change", () => { overlay.notify.min_score = {default: clampScore(range.value)}; changed(); });
  return el("div", {},
    el("div", {class: "sens"}, range, val),
    el("div", {class: "sens-ends"},
      el("span", {text: T("◀ more notifications")}),
      el("span", {text: T("fewer false alarms ▶")})),
    effect);
}

function renderQuestions() {
  const box = $("questions");
  box.innerHTML = "";
  if ((data.chats || []).length > 1) {
    box.append(question(T("Who receives the notifications?"), null,
      CONTROLS.chips(FIELDS()[1], overlay.notify.chats, (v) => { overlay.notify.chats = v; changed(); },
        {disabled: false, options: data.chats})));
  }
  const more = moreBox("questions", T("More choices: bursts, sensitivity…"));
  for (const q of QUESTIONS()) {
    if (q.mode && q.mode !== data.mode) continue;
    if (q.presence && !data.presence) continue;
    (q.more ? more : box).append(question(q.title, q.hint, pills(q.options, null)));
  }
  // Labels Frigate knows ("clio 3 océane", "ohana"…): ignore them, or only keep the
  // unknown ones.
  const subs = data.sub_labels || [];
  if (subs.length || (overlay.notify.ignore_sub_labels || []).length || overlay.notify.ignore_known) {
    const known = !!overlay.notify.ignore_known;
    const content = el("div", {},
      pills([
        {label: T("Report everything"), patch: {ignore_known: false}},
        {label: T("🏷 Only unknown objects"), patch: {ignore_known: true}},
      ], null));
    if (!known) {
      content.append(el("div", {class: "hint", text: T("Don't notify for:")}),
        CONTROLS.chips(FIELDS().find((f) => f.key === "ignore_sub_labels"), overlay.notify.ignore_sub_labels,
          (v) => { overlay.notify.ignore_sub_labels = v; changed(); }, {disabled: false, options: subs.slice().sort()}));
    }
    more.append(question(T("Known labels"),
      T("Frigate takes a few seconds to recognize an object: with a label filter, notifications wait up to 5 s for it."),
      content));
  }
  // The score only exists in events mode: Frigate gives none for a review.
  if (data.mode !== "reviews") {
    more.append(question(T("Sensitivity"),
      T("Frigate's confidence that the object is real. Higher = fewer false alarms, but more risk of missing something."),
      sensitivity()));
  }
  if (more.children.length > 1) box.append(more);
}

// ---- recipients -----------------------------------------------------------------
//
// Each recipient can restrict what they receive: some objects, some times. Empty,
// they receive everything the cameras send them.

const DAY = [{from: "07:00", to: "22:00"}];

const RECIPIENT_OBJECTS = () => [
  {label: T("Everything"), patch: {labels: []}},
  {label: T("🚶 People"), patch: {labels: ["person"]}},
  {label: T("🚶🚗 People and cars"), patch: {labels: ["car", "person"]}},
];

const RECIPIENT_WHEN = () => [
  {label: T("All the time"), patch: {quiet_hours: [], off_hours: []}},
  {label: T("🌙 Only at night"), patch: {quiet_hours: [], off_hours: DAY}},
  {label: T("☀️ Only during the day"), patch: {quiet_hours: [], off_hours: NIGHT}},
  {label: T("🔕 Silent at night"), patch: {quiet_hours: NIGHT, off_hours: []}},
];

function recipientValues(chat) {
  const r = overlay.recipients[chat] || {};
  return {labels: r.labels || [], quiet_hours: r.quiet_hours || [], off_hours: r.off_hours || []};
}

function setRecipient(chat, patch) {
  const r = Object.assign(recipientValues(chat), clone(patch));
  for (const k of Object.keys(r)) if (!r[k].length) delete r[k];
  if (Object.keys(r).length) overlay.recipients[chat] = r;
  else delete overlay.recipients[chat];
  changed();
}

function recipientPills(chat, options) {
  const eff = recipientValues(chat);
  const wrap = el("div", {class: "pills"});
  let any = false;
  for (const o of options) {
    const active = !any && matches(o.patch, eff);
    any = any || active;
    wrap.append(el("button", {type: "button", class: "pill", "aria-pressed": String(active), text: o.label,
      onclick: () => setRecipient(chat, o.patch)}));
  }
  if (!any) wrap.append(el("span", {class: "pill custom", "aria-pressed": "true", text: T("Custom")}));
  return wrap;
}

function renderRecipients() {
  const chats = data.chats || [];
  $("recipients-box").hidden = chats.length < 2;
  const box = $("recipients");
  box.innerHTML = "";
  if (chats.length < 2) return;
  // Everyone receives everything until a restriction is set: folded until then.
  const restricted = Object.values(overlay.recipients || {}).some((r) =>
    (r.labels || []).length || (r.quiet_hours || []).length || (r.off_hours || []).length);
  const more = moreBox("recipients", T("Choose per person"), restricted);
  box.append(more);
  for (const chat of chats) {
    more.append(el("div", {class: "recipient"},
      el("div", {class: "who", text: "👤 " + chat}),
      el("div", {class: "sub-q", text: T("Receives")}), recipientPills(chat, RECIPIENT_OBJECTS()),
      el("div", {class: "sub-q", text: T("When")}), recipientPills(chat, RECIPIENT_WHEN())));
  }
}

// ---- cameras --------------------------------------------------------------------

function cameraSummary(name) {
  const eff = effective(name);
  if (eff.enabled === false) return T("disabled");
  const n = Object.keys(overlay.cameras[name]).length;
  const st = STYLES().find((s) => matches(s.patch, eff));
  const bits = [st ? st.label : T("custom style")];
  const labels = eff.labels || [];
  bits.push(labels.length ? labels.join(", ") : T("all objects"));
  if ((eff.zones || []).length) bits.push("📍 " + eff.zones.join(", "));
  if (!n) bits.push(T("default"));
  if (untracked(name).length) bits.unshift(T("⚠️ object not tracked by Frigate"));
  const mute = live && live.mutes.find((m) => m.camera === name);
  if (mute) bits.unshift(T("🔇 muted ") + untilText(mute.until));
  return bits.join(" · ");
}

// untracked lists the requested objects Frigate does not track on the camera. Empty
// if Frigate did not give its list (unreachable): we don't know, we say nothing.
function untracked(name) {
  const info = (data.cameras || []).find((c) => c.name === name);
  if (!info || !info.labels || !info.labels.length) return [];
  return (effective(name).labels || []).filter((l) => !info.labels.includes(l));
}

function renderCameras() {
  const box = $("cameras");
  const open = new Set([...box.querySelectorAll("details[open]")].map((d) => d.dataset.name));
  const openMore = new Set([...box.querySelectorAll("details.more[open]")].map((d) => d.dataset.name));
  box.innerHTML = "";
  const names = (data.cameras || []).map((c) => c.name);
  for (const name of Object.keys(overlay.cameras)) if (!names.includes(name)) names.push(name);
  if (!names.length) {
    box.append(el("div", {class: "body"}, el("p", {class: "hint", text: T("No known camera.")})));
    return;
  }
  for (const name of names.sort()) {
    if (!overlay.cameras[name]) overlay.cameras[name] = {};
    const eff = effective(name);
    const on = eff.enabled !== false;

    const input = el("input", {type: "checkbox", "aria-label": T("Notifications for ") + name});
    input.checked = on;
    input.addEventListener("click", (e) => e.stopPropagation()); // do not open/close the camera
    input.addEventListener("change", () => { apply({enabled: input.checked}, name); changed(); });
    const toggle = el("label", {class: "toggle", onclick: (e) => e.stopPropagation()}, input, el("span"));

    const d = el("details", {class: "camera" + (on ? "" : " off"), "data-name": name});
    if (open.has(name)) d.open = true;
    d.append(el("summary", {}, toggle, el("span", {class: "cam-name", text: name}),
      el("span", {class: "cam-state", text: cameraSummary(name)})));

    const body = el("div", {class: "body"});
    body.append(question(T("Notification style"), null,
      pills(STYLES().map((s) => ({label: s.label, patch: s.patch})), name)));
    const q = question(T("What should be reported?"), null, pills(QUESTIONS()[0].options, name));
    const missing = untracked(name);
    if (missing.length) {
      const list = missing.map((l) => Tf("“%s”", l)).join(", ");
      q.append(el("p", {class: "warn-line", text: Tf(
        "⚠️ Frigate doesn't track %s on this camera: these objects will never be reported. Add them to objects.track in Frigate's configuration.", list)}));
    }
    body.append(q);
    if (data.presence) {
      const hq = QUESTIONS().find((q) => q.presence);
      body.append(question(hq.title, T("E.g. keep outdoor cameras on while you're home."), pills(hq.options, name)));
    }
    const zones = unionOf("zones", name);
    if (zones.length) {
      body.append(question(T("Where?"), T("Only when the object enters one of the chosen zones (defined in Frigate)."),
        zonePills(name, zones)));
    }
    if (data.can_test && on) body.append(el("div", {class: "question"}, testButton(name, T("📨 Test this camera"))));

    const more = el("details", {class: "more", "data-name": name});
    if (openMore.has(name)) more.open = true;
    more.append(el("summary", {text: T("All settings for ") + name}));
    renderGrouped(more, name);
    more.append(el("div", {class: "row"},
      el("button", {type: "button", class: "link", text: T("Reset everything to default"),
        onclick: () => { overlay.cameras[name] = {}; changed(); }})));
    body.append(more);
    d.append(body);
    box.append(d);
  }
}

// ---- detailed editor (advanced settings) --------------------------------------

// Empty value per type. It serves when the global level has nothing to inherit:
// sending null would mean overriding nothing at all, since the server treats null as "missing".
const EMPTY = {bool: false, chips: [], ranges: [], duration: "0s", score: {default: 0}, choice: "skip"};

function defaultFor(field, inherited) {
  return clone(inherited === undefined || inherited === null ? EMPTY[field.type] : inherited);
}

// Each builder returns an element; `on(v)` reports the new value.
const CONTROLS = {
  choice(field, value, on, ctx) {
    const sel = el("select", {onchange: () => on(sel.value)});
    sel.disabled = ctx.disabled;
    for (const [v, label] of field.choices()) {
      const o = el("option", {value: v, text: label});
      if (v === (value || "skip")) o.selected = true;
      sel.append(o);
    }
    return sel;
  },

  bool(field, value, on, ctx) {
    const input = el("input", {type: "checkbox"});
    input.checked = !!value;
    input.disabled = ctx.disabled;
    input.setAttribute("aria-label", field.name);
    input.addEventListener("change", () => on(input.checked));
    return el("label", {class: "toggle"}, input, el("span"));
  },

  duration(field, value, on, ctx) {
    const input = el("input", {type: "text", class: "dur", placeholder: "60s", pattern: DUR.source});
    input.value = value || "0s";
    input.disabled = ctx.disabled;
    input.addEventListener("change", () => {
      if (!DUR.test(input.value.trim())) { input.reportValidity(); return; }
      on(input.value.trim());
    });
    return input;
  },

  chips(field, value, on, ctx) {
    const selected = Array.isArray(value) ? value.slice() : [];
    const known = ctx.options.slice();
    for (const v of selected) if (!known.includes(v)) known.push(v);
    const wrap = el("div", {class: "chips"});
    for (const opt of known) {
      const active = selected.includes(opt);
      const b = el("button", {
        type: "button", class: "chip", "aria-pressed": String(active), text: opt,
        onclick: () => {
          if (ctx.disabled) return;
          const next = selected.includes(opt) ? selected.filter((x) => x !== opt) : selected.concat([opt]);
          on(next);
        },
      });
      if (ctx.disabled) b.disabled = true;
      wrap.append(b);
    }
    if (field.free && !ctx.disabled) {
      const add = el("input", {type: "text", placeholder: T("add…"), size: "12"});
      add.addEventListener("change", () => {
        const v = add.value.trim();
        if (v && !selected.includes(v)) on(selected.concat([v]));
        add.value = "";
      });
      wrap.append(add);
    }
    if (!known.length && ctx.disabled) wrap.append(el("span", {class: "hint", text: T("none")}));
    return wrap;
  },

  score(field, value, on, ctx) {
    const v = value && typeof value === "object" ? value : {default: 0};
    const byLabel = v.by_label && Object.keys(v.by_label).length ? v.by_label : null;
    const rows = el("div", {class: "rows"});

    const sel = el("select", {onchange: () => {
      on(sel.value === "global" ? {default: 0.7} : {default: 0, by_label: {[ctx.options[0] || "person"]: 0.7}});
    }});
    sel.disabled = ctx.disabled;
    for (const [val, label] of [["global", T("One value for every object")], ["label", T("One value per object")]]) {
      const o = el("option", {value: val, text: label});
      if ((val === "label") === !!byLabel) o.selected = true;
      sel.append(o);
    }
    rows.append(el("div", {class: "row"}, sel));

    if (!byLabel) {
      const n = el("input", {type: "number", min: "0", max: "1", step: "0.05"});
      n.value = v.default ?? 0;
      n.disabled = ctx.disabled;
      n.addEventListener("change", () => on({default: clampScore(n.value)}));
      rows.append(el("div", {class: "row"}, n, el("span", {class: "hint", text: T("0 = no filter, 1 = certainty")})));
    } else {
      for (const [label, score] of Object.entries(byLabel)) {
        const n = el("input", {type: "number", min: "0", max: "1", step: "0.05"});
        n.value = score;
        n.disabled = ctx.disabled;
        n.addEventListener("change", () => {
          const next = Object.assign({}, byLabel, {[label]: clampScore(n.value)});
          on({default: 0, by_label: next});
        });
        const del = el("button", {type: "button", class: "icon", text: "✕", title: T("Remove"),
          onclick: () => {
            const next = Object.assign({}, byLabel); delete next[label];
            on(Object.keys(next).length ? {default: 0, by_label: next} : {default: 0.7});
          }});
        del.disabled = ctx.disabled;
        rows.append(el("div", {class: "row"}, el("span", {class: "lbl", text: label}), n, del));
      }
      const remaining = ctx.options.filter((o) => !(o in byLabel));
      if (remaining.length && !ctx.disabled) {
        const sel2 = el("select", {onchange: () => {
          if (!sel2.value) return;
          on({default: 0, by_label: Object.assign({}, byLabel, {[sel2.value]: 0.7})});
        }});
        sel2.append(el("option", {value: "", text: T("Add an object…")}));
        for (const o of remaining) sel2.append(el("option", {value: o, text: o}));
        rows.append(el("div", {class: "row"}, sel2));
      }
      rows.append(el("p", {class: "hint", text: T("An object missing from this list isn't filtered on score.")}));
    }
    return rows;
  },

  ranges(field, value, on, ctx) {
    const list = Array.isArray(value) ? value : [];
    const rows = el("div", {class: "rows"});
    list.forEach((r, i) => {
      const from = el("input", {type: "time"}); from.value = r.from; from.disabled = ctx.disabled;
      const to = el("input", {type: "time"}); to.value = r.to; to.disabled = ctx.disabled;
      const upd = () => {
        const next = clone(list);
        next[i] = {from: from.value, to: to.value};
        on(next);
      };
      from.addEventListener("change", upd);
      to.addEventListener("change", upd);
      const del = el("button", {type: "button", class: "icon", text: "✕", title: T("Remove"),
        onclick: () => on(list.filter((_, j) => j !== i))});
      del.disabled = ctx.disabled;
      rows.append(el("div", {class: "row"}, el("span", {text: T("from")}), from, el("span", {text: T("to")}), to, del));
    });
    if (!ctx.disabled) {
      rows.append(el("div", {class: "row"},
        el("button", {type: "button", class: "link", text: T("+ Add a range"),
          onclick: () => on(list.concat([{from: "22:00", to: "07:00"}]))})));
    } else if (!list.length) {
      rows.append(el("span", {class: "hint", text: T("no range")}));
    }
    return rows;
  },
};

function clampScore(v) {
  const n = Number(v);
  if (!isFinite(n)) return 0;
  return Math.min(1, Math.max(0, Math.round(n * 100) / 100));
}

function optionsFor(field, camera) {
  switch (field.source) {
    case "chats": return data.chats || [];
    case "severity": return ["alert", "detection"];
    case "labels": return unionOf("labels", camera);
    case "zones": return unionOf("zones", camera);
    case "sub_labels": return (data.sub_labels || []).slice().sort();
    default: return [];
  }
}

// unionOf gathers the values offered: those of the camera, or those of every
// camera for the default settings.
function unionOf(kind, camera) {
  const cams = camera ? (data.cameras || []).filter((c) => c.name === camera) : (data.cameras || []);
  const out = [];
  for (const c of cams) for (const v of c[kind] || []) if (!out.includes(v)) out.push(v);
  return out.sort();
}

// renderField draws a setting. Without `camera`, it applies to the default
// settings; with it, it applies to that camera's override and gets a "customize"
// box that creates or removes it.
function renderField(field, camera) {
  if (field.mode && field.mode !== data.mode) return null;
  if (field.presence && !data.presence) return null;
  if (field.globalOnly && camera) return null;

  const patch = camera ? overlay.cameras[camera] : overlay.notify;
  const inherited = camera ? overlay.notify[field.key] : undefined;
  const custom = !camera || field.key in patch;
  const value = custom ? patch[field.key] : inherited;

  const head = el("div", {class: "field-head"}, el("span", {class: "name", text: field.name}));
  if (camera) {
    head.append(el("span", {class: "spacer"}));
    const box = el("input", {type: "checkbox"});
    box.checked = custom;
    box.addEventListener("change", () => {
      if (box.checked) patch[field.key] = defaultFor(field, inherited);
      else delete patch[field.key];
      changed();
    });
    head.append(el("label", {class: "override"}, box, el("span", {text: T("customize")})));
  }

  const ctx = {disabled: !custom, options: optionsFor(field, camera)};
  const control = CONTROLS[field.type](field, value, (v) => {
    patch[field.key] = v;
    changed();
  }, ctx);

  const wrap = el("div", {class: "field"}, head, el("div", {class: "control" + (custom ? "" : " off")}, control));
  if (field.hint) wrap.append(el("p", {class: "hint", text: field.hint}));
  return wrap;
}

// renderGrouped adds the detailed settings to `box`, group by group; a group with
// no setting to show (mode, presence, camera) is left out.
function renderGrouped(box, camera) {
  const byKey = Object.fromEntries(FIELDS().map((f) => [f.key, f]));
  for (const g of GROUPS()) {
    if (g.globalOnly && camera) continue;
    const nodes = [];
    for (const k of g.keys) {
      if (camera && k === "enabled") continue; // already the camera's switch
      const node = renderField(byKey[k], camera);
      if (node) nodes.push(node);
    }
    if (g.extra) nodes.push(g.extra());
    if (nodes.length) box.append(el("div", {class: "fgroup"}, el("h3", {text: g.title}), ...nodes));
  }
}

function renderAdvanced() {
  const g = $("global");
  g.innerHTML = "";
  renderGrouped(g, null);
}

// ---- sommaire -------------------------------------------------------------------

function syncToc() {
  for (const a of document.querySelectorAll(".toc a")) {
    const target = $(a.dataset.target);
    a.parentElement.hidden = !target || target.hidden;
  }
}

// tocClicked: the link picked in the table of contents. A section at the bottom
// cannot scroll up under the header (the page ends before): it stays highlighted
// until the user scrolls by themselves.
let tocClicked = null;

// The "current" section is the last one whose top went under the header; at the
// bottom of the page, the last visible one.
function currentSection() {
  const links = [...document.querySelectorAll(".toc li:not([hidden]) a")];
  let current = links[0];
  for (const a of links) if ($(a.dataset.target).getBoundingClientRect().top <= 120) current = a;
  if (tocClicked && links.includes(tocClicked)) {
    current = tocClicked;
  } else if (window.innerHeight + window.scrollY >= document.documentElement.scrollHeight - 4) {
    current = links[links.length - 1];
  }
  for (const a of links) a.setAttribute("aria-current", String(a === current));
}

for (const a of document.querySelectorAll(".toc a")) {
  a.addEventListener("click", () => {
    if (a.dataset.target === "advanced") $("advanced").open = true;
    tocClicked = a;
    currentSection();
  });
}
for (const ev of ["wheel", "touchmove", "keydown"]) {
  window.addEventListener(ev, () => { tocClicked = null; }, {passive: true});
}
window.addEventListener("scroll", currentSection, {passive: true});

// welcome: show the first visit's message (redrawn in the page's language).
let welcome = false;

function render() {
  if (welcome) {
    message(T("Everything is ready: notifications already work with the settings below. Pick a style, then send yourself a sample to see what it looks like."), "info");
  }
  renderStyles();
  renderFraming();
  renderTry();
  renderQuestions();
  renderRecipients();
  renderCameras();
  renderAdvanced();
  syncToc();
  currentSection();
}

// ---- pause and resume -----------------------------------------------------------

let live = null; // response of /api/state

// presenceName: "homeassistant/person/alice/state" → "alice".
function presenceName(topic) {
  const p = topic.split("/");
  return p.length >= 2 && p[p.length - 1] === "state" ? p[p.length - 2] : p[p.length - 1];
}

function untilText(iso) {
  if (!iso) return T("until resumed");
  const d = new Date(iso);
  const opts = {timeZone: data.timezone, hour: "2-digit", minute: "2-digit"};
  const day = (x) => x.toLocaleDateString(locale(), {timeZone: data.timezone});
  if (day(d) !== day(new Date())) Object.assign(opts, {weekday: "long", day: "numeric", month: "long"});
  return T("until ") + d.toLocaleString(locale(), opts);
}

async function stateCall(path, body) {
  try {
    const resp = await api(path, {
      method: body ? "POST" : "GET",
      headers: body ? {"Content-Type": "application/json", "X-Requested-With": TOKEN} : {},
      body: body ? JSON.stringify(body) : undefined,
    });
    const v = await resp.json().catch(() => ({}));
    if (!resp.ok) throw new Error(v.error || "HTTP " + resp.status);
    // The camera summaries show the mutes: they are only redrawn if the mutes
    // changed, so as not to disturb an input in progress.
    const mutesChanged = JSON.stringify(live && live.mutes) !== JSON.stringify(v.mutes);
    live = v;
    renderLive();
    if (mutesChanged && overlay) renderCameras();
  } catch (e) {
    if (body) message(T("Action failed:\n") + e.message, "err");
  }
}

function renderLive() {
  const box = $("live");
  $("live").hidden = !live;
  stateBox();
  if (!live) return;
  box.innerHTML = "";
  box.className = "live" + (live.paused ? " paused" : "");
  if (live.paused) {
    box.append(el("span", {class: "state"}, el("span", {class: "dot paused"}),
        el("span", {text: T("Notifications paused ") + untilText(live.paused_until)})),
      el("button", {type: "button", class: "primary", text: T("▶ Resume"),
        onclick: () => stateCall("api/resume", {})}));
  } else {
    const seg = el("span", {class: "seg", role: "group", "aria-label": T("Pause")},
      el("span", {class: "hint", text: T("Pause:")}));
    for (const [label, minutes] of [["30 min", 30], ["1 h", 60], ["8 h", 480], [T("until resumed"), 0]]) {
      seg.append(el("button", {type: "button", text: label,
        onclick: () => stateCall("api/pause", {minutes})}));
    }
    box.append(el("span", {class: "state"}, el("span", {class: "dot ok pulse"}),
      el("span", {text: T("Notifications active")})), seg);
  }
  const sub = el("div", {class: "sub"});
  if (data && data.presence) {
    const home = (live.home || []).map(presenceName);
    sub.append(el("div", {class: "row"}, el("span", {text: home.length
      ? T("🏠 At home: ") + home.join(", ")
      : T("🚪 Nobody at home")})));
  }
  if (live.mutes.length) {
    for (const m of live.mutes) {
      sub.append(el("div", {class: "row"},
        el("span", {text: "🔇 " + m.camera + T(" muted ") + untilText(m.until)}),
        el("button", {type: "button", class: "link", text: T("Re-enable"),
          onclick: () => stateCall("api/resume", {camera: m.camera})})));
    }
  }
  if (sub.children.length) box.append(sub);
}

// ---- connection status ------------------------------------------------------------

let health = null; // response of /api/health
let refused = []; // Telegram users recently refused by the bot

async function loadHealth() {
  try {
    const resp = await api("api/health");
    if (!resp.ok) return;
    const body = await resp.json();
    health = body.components;
    refused = body.refused || [];
    renderHealth();
  } catch (e) { /* the status is a bonus: interrupt nothing */ }
}

// stateBox shows the status card as soon as one of its parts has something to say.
function stateBox() {
  $("state-box").hidden = !live && !health;
  syncToc();
}

function renderHealth() {
  $("health").hidden = !health;
  stateBox();
  if (!health) return;
  const line = $("health"), errors = $("health-errors");
  line.innerHTML = ""; errors.innerHTML = "";
  line.append(el("span", {class: "lbl", text: T("Connections")}));
  for (const c of health) {
    const comp = el("span", {class: "comp", title: c.detail || ""},
      el("span", {class: "dot " + c.state}), el("span", {class: "n", text: c.name}));
    if (c.state !== "error" && c.state !== "warn" && c.detail) comp.append(el("span", {class: "d", text: c.detail}));
    line.append(comp);
    if (c.state === "error" || c.state === "warn") {
      const box = el("div", {class: "health-error " + c.state}, el("b", {text: c.name + " — "}), document.createTextNode(c.detail));
      if (c.hint) box.append(el("div", {class: "fix", text: "👉 " + c.hint}));
      errors.append(box);
    }
  }
  if (refused.length) errors.append(refusedBox());
  errors.hidden = !errors.children.length;
}

// refusedBox lists the users the bot refused, with the ID to add to the
// configuration: that is how one finds one's own at installation.
function refusedBox() {
  const box = el("div", {class: "health-error warn"},
    el("b", {text: T("Telegram — users refused by the bot")}));
  const list = el("ul", {class: "refused"});
  for (const u of refused) {
    const who = [u.name, u.username && "@" + u.username].filter(Boolean).join(" ") || T("unknown");
    list.append(el("li", null, document.createTextNode(who + " · " + T("ID ")),
      el("code", {text: String(u.id)}), el("span", {class: "when", text: " · " + whenText(u.at)})));
  }
  box.append(list, el("div", {class: "fix", text: "👉 " + T(
    "To allow someone, add their ID to TELEGRAM_CHAT_ID (and to TELEGRAM_ADMINS if you set it), then restart the container.")}));
  return box;
}

// ---- recent activity ------------------------------------------------------------

const LABELS = {
  person: ["🚶", "Person"], car: ["🚗", "Car"], dog: ["🐕", "Dog"],
  cat: ["🐈", "Cat"], bicycle: ["🚲", "Bicycle"], motorcycle: ["🏍️", "Motorcycle"],
  bird: ["🐦", "Bird"], package: ["📦", "Package"],
};

function labelText(l) {
  const x = LABELS[l];
  return x ? x[0] + " " + T(x[1]) : "🔔 " + (l || T("Detection"));
}

// Reason for a filtering in plain words; `fix` tells whether a camera setting can do something about it.
const REASONS = () => ({
  camera_disabled: {text: T("camera disabled"), fix: true},
  false_positive: {text: T("false positive according to Frigate")},
  stationary: {text: T("stationary object"), fix: true},
  severity: {text: T("severity not selected"), fix: true},
  label: {text: T("object type not selected"), fix: true},
  score: {text: T("score too low"), fix: true},
  zone: {text: T("outside the chosen zones"), fix: true},
  paused: {text: T("notifications paused")},
  muted: {text: T("camera muted")},
  home: {text: T("someone was home"), fix: true},
  recipients: {text: T("no recipient for this object or at this time")},
  sub_label: {text: T("ignored label"), fix: true},
  off_hours: {text: T("during off hours"), fix: true},
  cooldown: {text: T("already reported a moment ago"), fix: true},
});

let history = null;
let historyAll = false;

function whenText(iso) {
  const d = new Date(iso);
  const tz = {timeZone: data.timezone};
  const day = (x) => x.toLocaleDateString(locale(), tz);
  const time = d.toLocaleTimeString(locale(), Object.assign({hour: "2-digit", minute: "2-digit"}, tz));
  if (day(d) === day(new Date())) return time;
  const yesterday = new Date(Date.now() - 86400000);
  if (day(d) === day(yesterday)) return T("yesterday ") + time;
  return d.toLocaleDateString(locale(), Object.assign({day: "numeric", month: "short"}, tz)) + " " + time;
}

// openCamera expands a camera and brings the page to it.
function openCamera(name) {
  const d = document.querySelector('details.camera[data-name="' + CSS.escape(name) + '"]');
  if (!d) return;
  d.open = true;
  d.scrollIntoView({behavior: "smooth", block: "start"});
}

async function loadHistory() {
  try {
    const resp = await api("api/history");
    if (!resp.ok) return;
    const first = history === null;
    history = (await resp.json()).entries;
    renderHistory();
    if (first && overlay) renderQuestions(); // the effect of the sensitivity slider depends on the history
  } catch (e) { /* the activity is a bonus: interrupt nothing */ }
}

function renderHistory() {
  $("activity-box").hidden = !history;
  syncToc();
  if (!history) return;
  const list = $("activity");
  list.innerHTML = "";
  const shown = historyAll ? history : history.slice(0, 8);
  if (!history.length) {
    list.append(el("li", {}, el("span", {class: "hint", text: T("No detection since the service started.")})));
  }
  for (const e of shown) {
    let thumb;
    if (e.has_thumb) {
      thumb = el("img", {class: "thumb", loading: "lazy", alt: "", src: "api/history/" + encodeURIComponent(e.id) + "/thumb"});
      thumb.addEventListener("error", () => thumb.replaceWith(el("span", {class: "thumb", text: (LABELS[e.label] || ["🔔"])[0]})));
    } else {
      thumb = el("span", {class: "thumb", text: (LABELS[e.label] || ["🔔"])[0]});
    }
    const details = [e.camera];
    if (e.zones && e.zones.length) details.push("📍 " + e.zones.join(", "));
    if (e.score) details.push(Math.round(e.score * 100) + T("%"));
    details.push(whenText(e.at));

    const out = el("div", {class: "out"});
    if (e.sent) {
      out.append(el("span", {class: "ok", text: e.grouped ? T("📦 Grouped") : T("✅ Sent")}));
    } else {
      const r = REASONS()[e.reason] || {text: e.reason || T("ignored")};
      out.append(el("span", {class: "no", text: "⛔ " + r.text}));
      if (r.fix && overlay && overlay.cameras[e.camera]) {
        out.append(el("br"), el("button", {type: "button", class: "link", text: T("Adjust ") + e.camera,
          onclick: () => openCamera(e.camera)}));
      }
    }
    list.append(el("li", {}, thumb,
      el("div", {class: "what"}, el("div", {class: "t", text: labelText(e.label) + (e.sub_label ? " · 🏷 " + e.sub_label : "")}), el("div", {class: "d", text: details.join(" · ")})),
      out));
  }
  const foot = $("activity-foot");
  foot.innerHTML = "";
  if (history.length) {
    const sent = history.filter((e) => e.sent).length;
    const ignored = history.length - sent;
    foot.append(el("span", {text: Tf("Out of the last %d detections: %d sent, %d ignored.", history.length, sent, ignored)}));
    if (history.length > 8) {
      foot.append(el("button", {type: "button", class: "link", text: historyAll ? T("Show less") : T("Show all"),
        onclick: () => { historyAll = !historyAll; renderHistory(); }}));
    }
  }
}

// ---- loading and saving -----------------------------------------------------------

// toSend removes the cameras without any override: they follow the default settings
// and have nothing to do in the saved file.
function toSend() {
  const cameras = {};
  for (const [name, patch] of Object.entries(overlay.cameras)) {
    if (Object.keys(patch).length) cameras[name] = patch;
  }
  return {notify: overlay.notify, cameras, recipients: overlay.recipients, external_url: overlay.external_url};
}

async function load() {
  const resp = await api("api/settings", {headers: {"Accept": "application/json"}});
  if (!resp.ok) throw new Error("HTTP " + resp.status + " : " + (await resp.text()));
  data = await resp.json();
  overlay = {notify: data.overlay.notify, cameras: data.overlay.cameras || {}, recipients: data.overlay.recipients || {},
    external_url: data.overlay.external_url || ""};
  // Each known camera gets an entry (empty = follows the global level) before the
  // saved state is recorded, otherwise the page would think it was modified on opening.
  for (const c of data.cameras || []) if (!overlay.cameras[c.name]) overlay.cameras[c.name] = {};
  $("mode").textContent = T("mode ") + data.mode;
  $("tz").textContent = data.timezone;
  $("connection").hidden = !data.can_connection;
  $("reset").hidden = !data.custom;
  // Set on the setup page, there is no config.yml: going back means the defaults.
  $("reset").dataset.t = data.can_connection ? "Back to the default settings" : "Back to the config.yml settings";
  $("reset").textContent = T($("reset").dataset.t);
  // First visit: nothing saved yet, everything works with the defaults.
  welcome = !data.warning && !data.custom && data.can_test;
  message(data.warning || "", "warn");
  saved = JSON.stringify(overlay);
  if (data.can_pause) await stateCall("api/state");
  if (data.can_history) await loadHistory();
  if (data.can_health) loadHealth(); // may take a few seconds (MQTT probe): don't wait
  render();
  touched();
}

// saving: the save in progress, if any; saves never overlap.
let saving = null;

// save sends the settings if they changed since the last save. Returns false if the
// server refused them.
async function save() {
  clearTimeout(saveTimer);
  while (saving) await saving;
  if (!dirty()) return true;
  const sent = JSON.stringify(overlay);
  let ok = false;
  saving = (async () => {
    try {
      const resp = await api("api/settings", {
        method: "PUT",
        headers: {"Content-Type": "application/json", "X-Requested-With": TOKEN},
        body: JSON.stringify(toSend()),
      });
      const body = await resp.json().catch(() => ({}));
      if (!resp.ok) throw new Error(body.error || "HTTP " + resp.status);
      saved = sent;
      ok = true;
      message("", "");
      if (!data.custom) {
        data.custom = true;
        $("reset").hidden = false;
      }
      status(T("Saved ✓ — applied immediately"), "saved");
    } catch (e) {
      message(T("Save refused:\n") + e.message, "err");
      status(T("Not saved"), "dirty");
    }
  })();
  await saving;
  saving = null;
  // Changed while it was being sent: one more save.
  if (ok && dirty()) touched();
  return ok;
}

// flush saves what is pending right away; false if the settings were refused.
async function flush() {
  if (saving) await saving;
  return dirty() ? save() : true;
}

async function reset() {
  const question = data.can_connection
    ? T("Go back to the default settings? The choices made on this page will be lost.")
    : T("Delete the settings saved here and go back to the config.yml ones?");
  if (!confirm(question)) return;
  try {
    const resp = await api("api/settings/reset", {method: "POST", headers: {"X-Requested-With": TOKEN}});
    if (!resp.ok) {
      const body = await resp.json().catch(() => ({}));
      throw new Error(body.error || "HTTP " + resp.status);
    }
    await load();
  } catch (e) {
    message(T("Could not go back to config.yml:\n") + e.message, "err");
  }
}

$("reset").addEventListener("click", reset);
// Leaving with a save pending: it is sent at once, the browser asks to wait for it.
window.addEventListener("beforeunload", (e) => {
  if (!dirty()) return;
  save();
  e.preventDefault();
});

// One button per language of the catalogs.
for (const l of LANGUAGES) {
  const b = el("button", {type: "button", "data-lang": l.code, "aria-pressed": "false", title: l.name, text: l.code.toUpperCase()});
  b.addEventListener("click", () => setLang(l.code));
  document.querySelector(".lang").append(b);
}
applyStatic();
load().catch((e) => message(T("Loading failed:\n") + e.message, "err"));
// The pause can also change from Telegram: refresh the banner.
setInterval(() => {
  if (!data || document.hidden) return;
  if (data.can_pause) stateCall("api/state");
  if (data.can_history) loadHistory();
  if (data.can_health) loadHealth();
}, 30000);
